import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { api } from '../config/api';
import { useAuth } from '../context/AuthContext';
import { useConfirm } from '../context/ConfirmContext';
import { useToast } from '../context/ToastContext';
import Panel from '../components/Panel';
import BoundaryEditor from '../components/BoundaryEditor';

const MONO = "Consolas, 'IBM Plex Mono', monospace";
const C = { purple: '#a896d6', green: '#5CD685', red: '#D65C5C', amber: '#D6A05C', text: 'rgba(255,255,255,.78)', textDim: 'rgba(255,255,255,.50)', border: 'rgba(255,255,255,.07)', bg: '#120c1e' };

function ApplicationDetail() {
  const { id } = useParams();
  const toast = useToast();
  const { user } = useAuth();
  const confirm = useConfirm();
  const navigate = useNavigate();
  const [app, setApp] = useState(null);
  const [history, setHistory] = useState([]);
  const [comments, setComments] = useState([]);
  const [newComment, setNewComment] = useState('');
  const [isInternal, setIsInternal] = useState(false);
  const [postingComment, setPostingComment] = useState(false);
  const [emailPreview, setEmailPreview] = useState(null);
  const [testCreated, setTestCreated] = useState(null);

  // Review checklist state (persisted in app.review_checklist or local)
  const [checklist, setChecklist] = useState({
    org_verified: false,
    system_in_scope: false,
    contact_valid: false,
    application_complete: false,
  });
  const [rejectReason, setRejectReason] = useState('');
  const [showReject, setShowReject] = useState(false);
  const [requestInfoMsg, setRequestInfoMsg] = useState('');
  const [showRequestInfo, setShowRequestInfo] = useState(false);

  useEffect(() => {
    if (id) {
      api.get('/api/applications/' + id).then(res => {
        setApp(res.data);
        if (res.data.review_checklist) {
          setChecklist(prev => ({ ...prev, ...res.data.review_checklist }));
        }
      }).catch(console.error);
      api.get('/api/applications/' + id + '/history').then(res => setHistory(res.data)).catch(console.error);
      api.get('/api/applications/' + id + '/comments').then(res => setComments(res.data)).catch(console.error);
    }
  }, [id]);

  const refreshApp = async () => {
    try {
      const res = await api.get('/api/applications/' + id);
      setApp(res.data);
      const hRes = await api.get('/api/applications/' + id + '/history');
      setHistory(hRes.data);
    } catch (err) { console.error('Refresh failed:', err); }
  };

  // --- Email preview & state changes ---
  const showEmailPreviewFor = async (newState, label) => {
    try {
      const res = await api.get('/api/applications/' + id + '/email-preview?new_state=' + newState);
      setEmailPreview({ ...res.data, label, newState });
    } catch (err) { toast.show('Preview failed', 'error'); }
  };

  const confirmStateChange = async () => {
    if (!emailPreview) return;
    try {
      await api.patch('/api/applications/' + id + '/state?new_state=' + emailPreview.newState);
      // Auto-schedule CAT-72 on approval (API key auto-generated by backend)
      if (emailPreview.newState === 'approved') {
        try { await api.post('/api/cat72/tests', { application_id: parseInt(id) }); toast.show('CAT-72 test auto-scheduled', 'success'); } catch (e) { console.error('Auto-schedule CAT-72:', e.message); }
      }
      setEmailPreview(null);
      await refreshApp();
      toast.show('State changed to ' + emailPreview.newState, 'success');
    } catch (err) { toast.show('Failed: ' + (err.response?.data?.detail || err.message), 'error'); }
  };

  const handleQuickState = async (newState, label) => {
    if (!await confirm({ title: 'Change State', message: label + '?' })) return;
    try {
      await api.patch('/api/applications/' + id + '/state?new_state=' + newState);
      await refreshApp();
      toast.show('State updated', 'success');
    } catch (err) { toast.show('Failed: ' + (err.response?.data?.detail || err.message), 'error'); }
  };

  // --- Simple actions ---
  const handleBeginReview = async () => {
    if (!await confirm({ title: 'Begin Review', message: 'Move this application to In Review? The applicant will be notified that review has started.' })) return;
    try {
      await api.patch('/api/applications/' + id + '/state?new_state=under_review');
      await refreshApp();
      toast.show('Application moved to review', 'success');
    } catch (err) { toast.show('Failed: ' + (err.response?.data?.detail || err.message), 'error'); }
  };

  const handleApprove = () => showEmailPreviewFor('approved', 'Approve Application');
  const handleSuspend = () => showEmailPreviewFor('suspended', 'Withdraw Application');

  const handleReinstate = async () => {
    if (!await confirm({ title: 'Reinstate', message: 'Reinstate this application to pending?' })) return;
    try {
      await api.patch('/api/applications/' + id + '/state?new_state=pending');
      await refreshApp();
    } catch (err) { toast.show('Failed: ' + (err.response?.data?.detail || err.message), 'error'); }
  };

  const handleReject = async () => {
    if (!rejectReason.trim()) { toast.show('Please provide a reason', 'error'); return; }
    if (!await confirm({ title: 'Reject Application', message: 'Reject this application? This will notify the applicant with your reason.', danger: true, confirmLabel: 'Reject' })) return;
    try {
      await api.patch('/api/applications/' + id + '/state?new_state=rejected');
      await api.post('/api/applications/' + id + '/comments', { content: 'REJECTED: ' + rejectReason, is_internal: false });
      setShowReject(false);
      setRejectReason('');
      await refreshApp();
      toast.show('Application rejected', 'success');
    } catch (err) { toast.show('Failed: ' + (err.response?.data?.detail || err.message), 'error'); }
  };

  const handleRequestInfo = async () => {
    if (!requestInfoMsg.trim()) { toast.show('Please describe what info is needed', 'error'); return; }
    try {
      await api.post('/api/applications/' + id + '/comments', { content: 'INFO REQUESTED: ' + requestInfoMsg, is_internal: false });
      setShowRequestInfo(false);
      setRequestInfoMsg('');
      const cRes = await api.get('/api/applications/' + id + '/comments');
      setComments(cRes.data);
      toast.show('Request sent and logged', 'success');
    } catch (err) { toast.show('Failed: ' + (err.response?.data?.detail || err.message), 'error'); }
  };

  // --- Comments ---
  const handlePostComment = async () => {
    if (!newComment.trim()) return;
    setPostingComment(true);
    try {
      const res = await api.post('/api/applications/' + id + '/comments', { content: newComment, is_internal: isInternal });
      setComments(prev => [res.data, ...prev]);
      setNewComment('');
      setIsInternal(false);
      toast.show('Comment added', 'success');
    } catch (err) { toast.show('Failed: ' + (err.response?.data?.detail || err.message), 'error'); }
    setPostingComment(false);
  };

  const handleDeleteComment = async (commentId) => {
    try {
      await api.delete('/api/applications/' + id + '/comments/' + commentId);
      setComments(prev => prev.filter(c => c.id !== commentId));
      toast.show('Comment deleted', 'success');
    } catch (err) { toast.show('Failed: ' + (err.response?.data?.detail || err.message), 'error'); }
  };

  // --- Checklist toggle ---
  const toggleCheck = (key) => {
    setChecklist(prev => {
      const updated = { ...prev, [key]: !prev[key] };
      // Save to backend silently
      api.patch('/api/applicants/' + id, { review_checklist: updated }).catch(() => {});
      return updated;
    });
  };
  const allChecked = Object.values(checklist).every(Boolean);

  // --- Pipeline ---
  const PIPELINE_STAGES = [
    { key: 'pending', label: 'Pending', icon: '1' },
    { key: 'approved', label: 'Approved', icon: '2' },
    { key: 'testing', label: 'CAT-72', icon: '3' },
    { key: 'conformant', label: 'Certified', icon: '4' },
  ];
  const currentStageIdx = PIPELINE_STAGES.findIndex(s => s.key === app?.state);
  const isSuspended = app?.state === 'revoked' || app?.state === 'suspended' || app?.state === 'rejected' || app?.state === 'failed';

  const nextStepText = () => {
    switch (app?.state) {
      case 'pending': return 'New application. Review the organization and system, then approve or reject.';

      case 'approved': return 'Approved. Interlock credentials sent. CAT-72 auto-starts when Interlock connects.';
      case 'testing': return 'CAT-72 running. Certificate auto-issues on pass.';
      case 'conformant': return 'ODDC Conformance achieved. Certificate issued.';
      case 'rejected': return 'Application rejected. See comments for details.';
      case 'failed': return 'CAT-72 test failed. Re-approve to schedule another attempt.';
      case 'revoked': case 'suspended': return 'Application withdrawn. Contact info@sentinelauthority.org.';
      default: return '';
    }
  };

  const stateLabel = (s) => {
    const map = { approved: 'Approved', conformant: 'Certified', pending: 'Pending', testing: 'CAT-72 Running', rejected: 'Rejected', suspended: 'Withdrawn', revoked: 'Revoked', failed: 'Failed' };
    return map[s] || (s || '').replace(/_/g, ' ');
  };

  if (!app) return <div style={{ color: C.textDim }}>Loading...</div>;

  // ─── RENDER ───
  return (
    <div className="space-y-6">

      {/* ── Email Preview Modal (portaled) ── */}
      {emailPreview && ReactDOM.createPortal(
        <div onClick={() => setEmailPreview(null)} style={{ position: 'fixed', inset: 0, zIndex: 99999, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,.75)', backdropFilter: 'blur(4px)', WebkitBackdropFilter: 'blur(4px)' }}>
          <div onClick={e => e.stopPropagation()} style={{ background: 'rgba(18,12,30,0.95)', border: '1px solid rgba(157,140,207,0.12)', maxWidth: 'min(650px, 95vw)', width: '95%', maxHeight: '80vh', overflow: 'hidden', display: 'flex', flexDirection: 'column', position: 'relative' }}>
            <span style={{ position: 'absolute', top: -1, left: -1, width: 10, height: 10, borderTop: '1px solid rgba(157,140,207,0.3)', borderLeft: '1px solid rgba(157,140,207,0.3)' }} />
            <span style={{ position: 'absolute', top: -1, right: -1, width: 10, height: 10, borderTop: '1px solid rgba(157,140,207,0.3)', borderRight: '1px solid rgba(157,140,207,0.3)' }} />
            <span style={{ position: 'absolute', bottom: -1, left: -1, width: 10, height: 10, borderBottom: '1px solid rgba(157,140,207,0.3)', borderLeft: '1px solid rgba(157,140,207,0.3)' }} />
            <span style={{ position: 'absolute', bottom: -1, right: -1, width: 10, height: 10, borderBottom: '1px solid rgba(157,140,207,0.3)', borderRight: '1px solid rgba(157,140,207,0.3)' }} />
            <div style={{ padding: '20px 24px', borderBottom: '1px solid rgba(255,255,255,.04)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <h3 style={{ margin: 0, fontFamily: MONO, fontSize: '9px', letterSpacing: '3px', textTransform: 'uppercase', color: 'rgba(157,140,207,0.6)' }}>Email Preview</h3>
                <p style={{ margin: '4px 0 0', fontSize: '12px', color: C.textDim }}>This email will be sent to <strong style={{ color: 'rgba(255,255,255,.94)' }}>{emailPreview.to}</strong></p>
              </div>
              <button onClick={() => setEmailPreview(null)} style={{ background: 'none', border: 'none', color: 'rgba(255,255,255,.4)', cursor: 'pointer', fontSize: '16px', padding: '4px 8px' }}>✕</button>
            </div>
            <div style={{ padding: '16px 24px', borderBottom: '1px solid rgba(255,255,255,.04)' }}>
              <div style={{ fontFamily: MONO, fontSize: '9px', letterSpacing: '2px', textTransform: 'uppercase', color: 'rgba(255,255,255,.35)', marginBottom: '4px' }}>Subject</div>
              <div style={{ fontSize: '14px', color: 'rgba(255,255,255,.94)', fontWeight: 400 }}>{emailPreview.subject}</div>
            </div>
            <div style={{ flex: 1, overflow: 'auto', padding: '20px 24px' }}>
              <div style={{ background: '#fff', overflow: 'hidden' }} dangerouslySetInnerHTML={{ __html: emailPreview.html }} />
            </div>
            <div style={{ padding: '16px 24px', display: 'flex', justifyContent: 'flex-end', gap: '10px', borderTop: '1px solid rgba(255,255,255,.04)' }}>
              <button onClick={() => setEmailPreview(null)} style={{ padding: '8px 20px', background: 'transparent', border: '1px solid rgba(255,255,255,.06)', color: 'rgba(255,255,255,.5)', fontFamily: MONO, fontSize: '9px', letterSpacing: '1.5px', textTransform: 'uppercase', cursor: 'pointer' }}>Cancel</button>
              <button onClick={confirmStateChange} style={{ padding: '8px 20px', background: 'transparent', border: '1px solid ' + (emailPreview.newState === 'suspended' ? 'rgba(214,92,92,0.3)' : 'rgba(157,140,207,0.25)'), color: emailPreview.newState === 'suspended' ? C.red : 'rgba(157,140,207,0.9)', fontFamily: MONO, fontSize: '9px', letterSpacing: '1.5px', textTransform: 'uppercase', cursor: 'pointer' }}>
                {emailPreview.label} + Send Email
              </button>
            </div>
          </div>
        </div>,
        document.body
      )}

      {/* ── Top Bar ── */}
      <div className="flex items-center justify-between">
        <Link to="/applications" className="flex items-center gap-2 no-underline" style={{ color: C.textDim, fontFamily: MONO, fontSize: '11px', letterSpacing: '1px', textTransform: 'uppercase' }}>
          <ArrowLeft className="w-4 h-4" /> Back to Applications
        </Link>
        {user?.role === 'admin' && (
          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
            {app.state === 'pending' && <button onClick={handleApprove} className="px-4 py-2 btn" style={{ fontSize: '11px', color: C.green, borderColor: 'rgba(92,214,133,0.3)' }}>Approve &#8594;</button>}
            {app.state === 'pending' && <button onClick={() => setShowReject(!showReject)} className="px-3 py-2 btn" style={{ fontSize: '11px', color: C.red }}>Reject</button>}
            {(app.state === 'suspended' || app.state === 'revoked' || app.state === 'rejected') && <button onClick={handleReinstate} className="px-4 py-2 btn" style={{ fontSize: '11px', color: C.green, borderColor: 'rgba(92,214,133,0.3)' }}>Reinstate</button>}
            {['pending', 'approved'].includes(app.state) && <button onClick={handleSuspend} className="px-3 py-2 btn" style={{ fontSize: '10px', color: C.textDim, opacity: 0.5 }}>Withdraw</button>}
          </div>
        )}
      </div>

      {/* ── Progress Pipeline ── */}
      <Panel>
        <div style={{ padding: '8px 0' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px', marginBottom: '20px' }}>
            {PIPELINE_STAGES.map((stage, i) => {
              const isActive = stage.key === app.state;
              const isComplete = currentStageIdx > i;
              return (
                <React.Fragment key={stage.key}>
                  {i > 0 && <div style={{ flex: 1, height: '2px', background: isComplete ? C.green : C.border, margin: '0 8px' }} />}
                  <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '8px', minWidth: '80px' }}>
                    <div style={{ width: '32px', height: '32px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: MONO, fontSize: '12px', fontWeight: 'bold', background: isComplete ? 'rgba(92,214,133,0.2)' : isActive ? 'rgba(157,140,207,0.25)' : 'rgba(255,255,255,0.03)', border: '2px solid ' + (isComplete ? C.green : isActive ? C.purple : C.border), color: isComplete ? C.green : isActive ? C.purple : C.textDim }}>
                      {isComplete ? '\u2713' : stage.icon}
                    </div>
                    <span style={{ fontFamily: MONO, fontSize: '9px', letterSpacing: '0.5px', textTransform: 'uppercase', color: isActive ? C.purple : isComplete ? C.green : C.textDim, textAlign: 'center' }}>{stage.label}</span>
                  </div>
                </React.Fragment>
              );
            })}
          </div>
          {isSuspended && (
            <div style={{ padding: '12px 16px', border: '1px solid ' + C.border, marginBottom: '12px' }}>
              <span style={{ color: C.red, fontFamily: MONO, fontSize: '11px' }}>&#9888; {app.state === 'rejected' ? 'REJECTED' : app.state === 'failed' ? 'FAILED' : 'WITHDRAWN'} — See comments for details.</span>
            </div>
          )}
          <div style={{ padding: '12px 16px', border: '1px solid ' + C.border }}>
            <span style={{ color: C.text, fontSize: '13px', lineHeight: '1.5' }}>{nextStepText()}</span>
          </div>
        </div>
      </Panel>

      {testCreated && (
        <div style={{ padding: '16px', border: '1px solid ' + C.border }}>
          <p style={{ color: C.green, fontFamily: MONO, fontSize: '12px', margin: 0 }}>
            CAT-72 Test Scheduled: {testCreated.test_id} — <Link to="/cat72" style={{ color: C.purple }}>Go to Console</Link>
          </p>
        </div>
      )}

      {/* ── App Header ── */}
      <div>
        <p style={{ fontFamily: MONO, fontSize: '10px', letterSpacing: '4px', textTransform: 'uppercase', color: C.purple, marginBottom: '8px' }}>Application {app.application_number}</p>
        <h1 style={{ fontFamily: "Georgia, 'Source Serif 4', serif", fontSize: 'clamp(24px, 4vw, 32px)', fontWeight: 200, letterSpacing: '-0.02em', margin: 0 }}>{app.system_name}</h1>
        <p style={{ color: C.text, marginTop: '8px' }}>{app.system_description}</p>
      </div>

      {/* ── Org + Status ── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Panel>
          <div className="hud-label" style={{ marginBottom: '16px' }}>Organization</div>
          <p style={{ color: 'rgba(255,255,255,.94)', fontSize: '18px', marginBottom: '8px' }}>{app.organization_name}</p>
          <p style={{ color: C.text, marginBottom: '4px' }}><strong>Contact:</strong> {app.contact_name}</p>
          <p style={{ color: C.text, marginBottom: '4px' }}><strong>Email:</strong> {app.contact_email}</p>
          {app.contact_phone && <p style={{ color: C.text }}><strong>Phone:</strong> {app.contact_phone}</p>}
        </Panel>
        <Panel>
          <div className="hud-label" style={{ marginBottom: '16px' }}>Status</div>
          <span style={{ fontFamily: MONO, fontSize: '12px', letterSpacing: '1px', textTransform: 'uppercase', color: app.state === 'approved' ? C.green : app.state === 'rejected' ? C.red : app.state === 'failed' ? C.red : app.state === 'suspended' ? C.red : C.amber }}>{stateLabel(app.state)}</span>
          <p style={{ color: C.text, marginTop: '12px' }}><strong>Submitted:</strong> {app.submitted_at ? new Date(app.submitted_at).toLocaleString() : 'N/A'}</p>
        </Panel>
      </div>


      {/* ══════════════════════════════════════════════
          DEPLOY PANEL — shows after approval
          ══════════════════════════════════════════════ */}
      {['approved', 'testing', 'conformant'].includes(app.state) && (
        <Panel>
          <div className="hud-label" style={{ marginBottom: '16px' }}>Deploy Interlock</div>
          <p style={{ color: C.text, fontSize: '13px', marginBottom: '20px' }}>
            {app.state === 'approved' ? 'Your application is approved. Deploy the Interlock to begin your CAT-72 certification test.' :
             app.state === 'testing' ? 'CAT-72 is running. Your Interlock is connected and reporting telemetry.' :
             'Certified. Your Interlock is actively enforcing boundaries.'}
          </p>

          {/* Step 1 */}
          <div style={{ marginBottom: '20px' }}>
            <div style={{ fontFamily: MONO, fontSize: '9px', letterSpacing: '2px', textTransform: 'uppercase', color: C.purple, marginBottom: '8px' }}>Step 1 — Install</div>
            <div style={{ background: 'rgba(0,0,0,.3)', border: '1px solid ' + C.border, padding: '12px 16px', fontFamily: MONO, fontSize: '13px', color: C.green, position: 'relative' }}>
              <span style={{ position: 'absolute', top: -1, left: -1, width: 8, height: 8, borderTop: '1px solid rgba(157,140,207,0.3)', borderLeft: '1px solid rgba(157,140,207,0.3)' }} />
              <span style={{ position: 'absolute', top: -1, right: -1, width: 8, height: 8, borderTop: '1px solid rgba(157,140,207,0.3)', borderRight: '1px solid rgba(157,140,207,0.3)' }} />
              <span style={{ position: 'absolute', bottom: -1, left: -1, width: 8, height: 8, borderBottom: '1px solid rgba(157,140,207,0.3)', borderLeft: '1px solid rgba(157,140,207,0.3)' }} />
              <span style={{ position: 'absolute', bottom: -1, right: -1, width: 8, height: 8, borderBottom: '1px solid rgba(157,140,207,0.3)', borderRight: '1px solid rgba(157,140,207,0.3)' }} />
              pip install envelo
            </div>
          </div>

          {/* Step 2 */}
          <div style={{ marginBottom: '20px' }}>
            <div style={{ fontFamily: MONO, fontSize: '9px', letterSpacing: '2px', textTransform: 'uppercase', color: C.purple, marginBottom: '8px' }}>Step 2 — Start</div>
            <div style={{ background: 'rgba(0,0,0,.3)', border: '1px solid ' + C.border, padding: '12px 16px', fontFamily: MONO, fontSize: '13px', color: C.green, position: 'relative' }}>
              <span style={{ position: 'absolute', top: -1, left: -1, width: 8, height: 8, borderTop: '1px solid rgba(157,140,207,0.3)', borderLeft: '1px solid rgba(157,140,207,0.3)' }} />
              <span style={{ position: 'absolute', top: -1, right: -1, width: 8, height: 8, borderTop: '1px solid rgba(157,140,207,0.3)', borderRight: '1px solid rgba(157,140,207,0.3)' }} />
              <span style={{ position: 'absolute', bottom: -1, left: -1, width: 8, height: 8, borderBottom: '1px solid rgba(157,140,207,0.3)', borderLeft: '1px solid rgba(157,140,207,0.3)' }} />
              <span style={{ position: 'absolute', bottom: -1, right: -1, width: 8, height: 8, borderBottom: '1px solid rgba(157,140,207,0.3)', borderRight: '1px solid rgba(157,140,207,0.3)' }} />
              <div>export ENVELO_API_KEY=<span style={{ color: C.amber }}>[your key from approval email]</span></div>
              <div style={{ marginTop: '4px' }}>envelo start</div>
            </div>
            <p style={{ color: C.textDim, fontSize: '11px', marginTop: '8px' }}>Your API key was sent to <strong style={{ color: C.text }}>{app.contact_email}</strong> on approval. Check your inbox.</p>
          </div>

          {/* Step 3 */}
          <div style={{ marginBottom: '20px' }}>
            <div style={{ fontFamily: MONO, fontSize: '9px', letterSpacing: '2px', textTransform: 'uppercase', color: C.purple, marginBottom: '8px' }}>Step 3 — Integrate</div>
            <div style={{ background: 'rgba(0,0,0,.3)', border: '1px solid ' + C.border, padding: '12px 16px', fontFamily: MONO, fontSize: '13px', color: C.text, position: 'relative' }}>
              <span style={{ position: 'absolute', top: -1, left: -1, width: 8, height: 8, borderTop: '1px solid rgba(157,140,207,0.3)', borderLeft: '1px solid rgba(157,140,207,0.3)' }} />
              <span style={{ position: 'absolute', top: -1, right: -1, width: 8, height: 8, borderTop: '1px solid rgba(157,140,207,0.3)', borderRight: '1px solid rgba(157,140,207,0.3)' }} />
              <span style={{ position: 'absolute', bottom: -1, left: -1, width: 8, height: 8, borderBottom: '1px solid rgba(157,140,207,0.3)', borderLeft: '1px solid rgba(157,140,207,0.3)' }} />
              <span style={{ position: 'absolute', bottom: -1, right: -1, width: 8, height: 8, borderBottom: '1px solid rgba(157,140,207,0.3)', borderRight: '1px solid rgba(157,140,207,0.3)' }} />
              <div style={{ color: C.textDim, fontSize: '11px', marginBottom: '8px' }}># Before any action, check boundaries</div>
              <div style={{ color: C.green }}>{"curl -X POST http://localhost:9090/enforce \\"}</div>
              <div style={{ color: C.green, paddingLeft: '20px' }}>{"  -d '{ \"speed\": 50, \"lat\": 30.5 }'"}</div>
              <div style={{ color: C.textDim, fontSize: '11px', marginTop: '12px', marginBottom: '8px' }}># Python integration</div>
              <div style={{ color: C.amber }}>@agent.enforce</div>
              <div style={{ color: C.text }}>{'def move(speed, position):'}</div>
              <div style={{ color: C.text, paddingLeft: '20px' }}>{'robot.actuate(speed, position)'}</div>
            </div>
          </div>

          {/* What happens next */}
          <div style={{ padding: '12px 16px', border: '1px solid ' + C.border, background: 'rgba(157,140,207,0.03)' }}>
            <div style={{ fontFamily: MONO, fontSize: '9px', letterSpacing: '2px', textTransform: 'uppercase', color: C.purple, marginBottom: '8px' }}>What happens automatically</div>
            <div style={{ display: 'grid', gap: '6px', fontSize: '12px', color: C.text }}>
              <div>&#10003; Interlock connects and downloads your boundaries</div>
              <div>&#10003; CAT-72 test starts on first heartbeat (72-hour timer)</div>
              <div>&#10003; Telemetry flows in real-time to this dashboard</div>
              <div>&#10003; Certificate auto-issues when CAT-72 passes</div>
            </div>
          </div>
        </Panel>
      )}

      {/* ── Reject Inline (shows when reject clicked) ── */}
      {showReject && app.state === 'pending' && (
        <Panel>
          <div style={{ fontFamily: 'IBM Plex Mono, monospace', fontSize: '10px', letterSpacing: '1px', textTransform: 'uppercase', color: '#d65c5c', marginBottom: '8px' }}>Reject Application</div>
          <textarea value={rejectReason} onChange={(e) => setRejectReason(e.target.value)} rows={3} placeholder="Reason for rejection..." style={{ width: '100%', background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)', color: 'rgba(255,255,255,.94)', fontSize: '13px', padding: '12px', fontFamily: 'inherit', resize: 'none', outline: 'none' }} />
          <div style={{ display: 'flex', gap: '8px', marginTop: '8px', justifyContent: 'flex-end' }}>
            <button onClick={() => { setShowReject(false); setRejectReason(''); }} className="px-3 py-2 btn" style={{ fontSize: '11px' }}>Cancel</button>
            <button onClick={handleReject} className="px-3 py-2 btn" style={{ fontSize: '11px', color: '#d65c5c', borderColor: 'rgba(214,92,92,.3)' }}>Reject</button>
          </div>
        </Panel>
      )}

      {/* ── System + Boundaries ── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Panel>
          <div className="hud-label" style={{ marginBottom: '16px' }}>System Details</div>
          <p style={{ color: C.text, marginBottom: '8px' }}><strong>Version:</strong> {app.system_version || 'N/A'}</p>
          <p style={{ color: C.text, marginBottom: '8px' }}><strong>Manufacturer:</strong> {app.manufacturer || 'N/A'}</p>
          {app.facility_location && <p style={{ color: C.text, marginBottom: '8px' }}><strong>Facility:</strong> {app.facility_location}</p>}
        </Panel>
        <Panel>
          <div className="hud-label" style={{ marginBottom: '16px' }}>Safety Boundaries</div>
          {(() => {
            const env = typeof app.envelope_definition === 'string' ? (() => { try { return JSON.parse(app.envelope_definition); } catch { return null; } })() : app.envelope_definition;
            const bounds = env?.boundaries || [];
            if (bounds.length === 0) return <p style={{ color: C.textDim, fontSize: '13px', fontStyle: 'italic' }}>No boundaries defined</p>;
            return (
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid ' + C.border }}>
                    {['Type', 'Constraint', 'Unit'].map(h => <th key={h} style={{ fontFamily: MONO, fontSize: '9px', letterSpacing: '1.5px', textTransform: 'uppercase', color: C.textDim, fontWeight: 400, padding: '8px 12px', textAlign: 'left' }}>{h}</th>)}
                  </tr>
                </thead>
                <tbody>
                  {bounds.map((b, i) => {
                    const constraint = b.max && b.min ? (b.min + ' - ' + b.max) : b.max ? ('<= ' + b.max) : b.min ? ('>= ' + b.min) : b.radius_m ? ('radius ' + b.radius_m + 'm') : b.corridors ? b.corridors.join(', ') : b.polygon || '-';
                    return (
                      <tr key={i} style={{ borderBottom: '1px solid rgba(255,255,255,.04)' }}>
                        <td style={{ padding: '8px 12px', fontFamily: MONO, fontSize: '11px', color: C.purple, textTransform: 'uppercase', letterSpacing: '0.5px' }}>{b.type}</td>
                        <td style={{ padding: '8px 12px', color: C.text, fontSize: '13px' }}>{constraint}</td>
                        <td style={{ padding: '8px 12px', fontFamily: MONO, fontSize: '11px', color: C.textDim }}>{b.unit || '-'}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            );
          })()}
        </Panel>
      </div>

      {/* Boundary Editor - only when no boundaries exist */}
      {user?.role === 'admin' && (() => {
        const env = typeof app.envelope_definition === 'string' ? (() => { try { return JSON.parse(app.envelope_definition); } catch { return null; } })() : app.envelope_definition;
        if (env?.boundaries?.length > 0) return null;
        return <BoundaryEditor applicationId={app.id} initialBoundaries={app.envelope_definition || {}} onSave={async (boundaries) => {
          try { await api.patch('/api/applicants/' + app.id, { envelope_definition: boundaries }); toast.show('Boundaries saved', 'success'); setApp({ ...app, envelope_definition: boundaries }); }
          catch (e) { toast.show('Failed: ' + e.message, 'error'); }
        }} />;
      })()}

      {/* ── ODD Spec ── */}
      <Panel>
        <div className="hud-label" style={{ marginBottom: '16px' }}>ODD Specification</div>
        {(() => {
          const odd = typeof app.odd_specification === 'string' ? (() => { try { return JSON.parse(app.odd_specification); } catch { return null; } })() : app.odd_specification;
          if (!odd || Object.keys(odd).length === 0) return <p style={{ color: C.textDim, fontSize: '13px', fontStyle: 'italic' }}>Not specified</p>;
          return (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0' }}>
              {Object.entries(odd).map(([k, v]) => (
                <div key={k} style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 12px', borderBottom: '1px solid rgba(255,255,255,.04)' }}>
                  <span style={{ fontFamily: MONO, fontSize: '10px', color: C.textDim, textTransform: 'uppercase', letterSpacing: '0.5px' }}>{k.replace(/_/g, ' ')}</span>
                  <span style={{ color: C.text, fontSize: '13px', textAlign: 'right' }}>{Array.isArray(v) ? v.join(', ') : typeof v === 'boolean' ? (v ? 'Yes' : 'No') : String(v)}</span>
                </div>
              ))}
            </div>
          );
        })()}
      </Panel>

      {/* ── State History ── */}
      {history.length > 0 && (
        <Panel>
          <div className="hud-label" style={{ marginBottom: '16px' }}>State Change History</div>
          <div style={{ position: 'relative', paddingLeft: '28px' }}>
            <div style={{ position: 'absolute', left: '8px', top: '4px', bottom: '4px', width: '2px', background: C.border }} />
            {history.map((entry, i) => {
              const ns = entry.details?.new_state;
              const color = ns === 'conformant' || ns === 'approved' ? C.green : ns === 'suspended' || ns === 'revoked' || ns === 'rejected' ? C.red : ns === 'under_review' || ns === 'testing' ? C.purple : entry.action === 'submitted' ? C.purple : C.amber;
              const label = ns ? ns.replace(/_/g, ' ') : (entry.action || '').replace(/_/g, ' ');
              const fromLabel = entry.details?.old_state?.replace(/_/g, ' ');
              const ts = entry.timestamp ? new Date(entry.timestamp) : null;
              return (
                <div key={i} style={{ position: 'relative', paddingBottom: i < history.length - 1 ? '20px' : '0' }}>
                  <div style={{ position: 'absolute', left: '-24px', top: '2px', width: '12px', height: '12px', borderRadius: '50%', background: color + '08', border: '2px solid ' + color }} />
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px' }}>
                    <div>
                      <span style={{ fontFamily: MONO, fontSize: '12px', fontWeight: 500, color: color, textTransform: 'uppercase', letterSpacing: '0.5px' }}>{label}</span>
                      {fromLabel && entry.action !== 'submitted' && <span style={{ fontFamily: MONO, fontSize: '10px', color: C.textDim, marginLeft: '8px' }}>from {fromLabel}</span>}
                      <div style={{ marginTop: '4px' }}><span style={{ fontSize: '12px', color: C.textDim }}>{entry.user_email}</span></div>
                    </div>
                    {ts && (
                      <div style={{ textAlign: 'right', flexShrink: 0 }}>
                        <div style={{ fontFamily: MONO, fontSize: '11px', color: C.textDim }}>{ts.toLocaleDateString()}</div>
                        <div style={{ fontFamily: MONO, fontSize: '10px', color: C.textDim }}>{ts.toLocaleTimeString()}</div>
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </Panel>
      )}

      {/* ── Comments ── */}
      <Panel>
        <div className="hud-label" style={{ marginBottom: '16px' }}>Comments & Notes</div>
        <div style={{ marginBottom: comments.length > 0 ? '20px' : '0' }}>
          <textarea value={newComment} onChange={(e) => setNewComment(e.target.value)} rows={3} placeholder="Add a comment or note..." className="w-full px-4 py-3 outline-none resize-none" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid ' + C.border, color: 'rgba(255,255,255,.94)', fontSize: '13px', fontFamily: 'inherit' }} onFocus={(e) => e.target.style.borderColor = C.purple} onBlur={(e) => e.target.style.borderColor = C.border} />
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px', marginTop: '8px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              {user?.role === 'admin' && (
                <button onClick={() => setIsInternal(!isInternal)} className="btn" style={{ padding: '4px 10px', color: isInternal ? C.green : C.textDim, borderColor: isInternal ? 'rgba(92,214,133,0.2)' : 'rgba(255,255,255,0.06)' }}>Internal {isInternal ? 'ON' : 'OFF'}</button>
              )}
            </div>
            <button onClick={handlePostComment} disabled={postingComment || !newComment.trim()} className="px-4 py-2 btn">{postingComment ? 'Posting...' : 'Post Comment'}</button>
          </div>
        </div>
        {comments.length > 0 && (
          <div style={{ borderTop: '1px solid ' + C.border, paddingTop: '16px' }}>
            {comments.map((c) => (
              <div key={c.id} style={{ padding: '12px 0', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px', marginBottom: '6px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span style={{ fontFamily: MONO, fontSize: '12px', color: c.user_role === 'admin' ? C.purple : C.text, fontWeight: 500 }}>{c.user_email}</span>
                    {c.user_role === 'admin' && <span style={{ fontFamily: MONO, fontSize: '9px', padding: '2px 6px', color: C.purple, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Admin</span>}
                    {c.is_internal && <span style={{ fontFamily: MONO, fontSize: '9px', padding: '2px 6px', color: C.amber, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Internal</span>}
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <span style={{ fontFamily: MONO, fontSize: '10px', color: C.textDim }}>{c.created_at ? new Date(c.created_at).toLocaleString() : ''}</span>
                    {(user?.role === 'admin' || user?.email === c.user_email) && (
                      <button onClick={() => handleDeleteComment(c.id)} style={{ background: 'none', border: 'none', color: C.textDim, cursor: 'pointer', fontSize: '12px', padding: '0', opacity: 0.5 }}>x</button>
                    )}
                  </div>
                </div>
                <p style={{ color: c.content?.startsWith('REJECTED:') ? C.red : c.content?.startsWith('INFO REQUESTED:') ? C.amber : C.text, fontSize: '13px', lineHeight: 1.6, margin: 0, whiteSpace: 'pre-wrap' }}>{c.content}</p>
              </div>
            ))}
          </div>
        )}
        {comments.length === 0 && !newComment && <p style={{ color: C.textDim, fontSize: '13px', fontStyle: 'italic', margin: 0 }}>No comments yet</p>}
      </Panel>

      {app.notes && (
        <Panel>
          <div className="hud-label" style={{ marginBottom: '16px' }}>Applicant Notes</div>
          <p style={{ color: C.text, lineHeight: 1.7, whiteSpace: 'pre-wrap' }}>{app.notes}</p>
        </Panel>
      )}
    </div>
  );
}

export default ApplicationDetail;
